[package]
name = "nadal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
rust-bert = "0.17.0"
serde = "1.0.137"
